swagger: "2.0"
info:
  description: "ReminderApp API Documentation"
  version: "0.0.0"
  title: "ReminderApp"
  host: "localhost"
  basePath: "/api/V0.0.0"
schemes:
  - "https"
  - "http"
# paths:
# Accounts
