swagger: "2.0"
info:
  description: "ReminderApp API Documentation"
  version: "0.0.0"
  title: "ReminderApp"
  host: "localhost"
  basePath: "/api/V0.0.0"
schemes:
  - "https"
  - "http"
paths:
  # Accounts
  /users/{user_id}/reminders/:
    $ref: "./reminders/reminder_list.yml"

  # Reminders
  /reminders/{id}/:
    $ref: "./reminders/reminder.yml"
  /reminders/:
    $ref: "./reminders/create_reminder.yml"
